postgres:
  restart: always
  image: postgres
  environment:
    - POSTGRES_PASSWORD=sentry
    - POSTGRES_USER=sentry
  volumes:
    - /var/lib/postgresql/data

redis:
  restart: always
  image: redis

sentry: &default
  container_name: compose-sentry
  restart: always
  image: sentry
  command: sentry start
  links:
    - postgres
    - redis
  ports:
    - "8081:9000"
  environment:
    SENTRY_DB_USER: sentry
    SENTRY_DB_PASSWORD: sentry
    SENTRY_DB_NAME: sentry

celerybeat:
  <<: *default
  image: sentry
  command: sentry celery beat
  ports: []

celeryworker:
  <<: *default
  image: sentry
  command: sentry celery worker
  ports: []

