postgres:
  container_name: compose-sentry-postgres
  restart: always
  image: postgres
  environment:
    - POSTGRES_PASSWORD=sentry
    - POSTGRES_USER=sentry
  volumes:
    - /var/lib/postgresql/data

redis:
  container_name: compose-sentry-redis
  restart: always
  image: redis

celerybeat:
  image: sentry
  command: sentry celery beat
  environment:
    SENTRY_DB_USER: sentry
    SENTRY_DB_PASSWORD: sentry
    SENTRY_DB_NAME: sentry
    SENTRY_SECRET_KEY: ''

celeryworker:
  image: sentry
  command: sentry celery worker
  environment:
    SENTRY_DB_USER: sentry
    SENTRY_DB_PASSWORD: sentry
    SENTRY_DB_NAME: sentry
    SENTRY_SECRET_KEY: ''

sentry:
  container_name: compose-sentry
  restart: always
  image: sentry
  command: sentry start
  links:
    - postgres
    - redis
  ports:
    - "8081:9000"
  environment:
    SENTRY_DB_USER: sentry
    SENTRY_DB_PASSWORD: sentry
    SENTRY_DB_NAME: sentry
    SENTRY_SECRET_KEY: ''
